import Head from "next/head";
import Image from "next/image";
import {
  Button,
  Card,
  Display,
  Divider,
  Fieldset,
  Grid,
  Page,
  Spacer,
  Text,
} from "@geist-ui/core";
import { useEffect, useState } from "react";

import moment from "moment";
import "moment/locale/de";
import { PickResult } from "../lib/peoplePicker";
import { useRouter } from "next/router";
import { GetServerSideProps } from "next";
import { hasValidAuth } from "../lib/login";

export const getServerSideProps: GetServerSideProps = async (context) => {
  if (!hasValidAuth(context)) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
      props: {},
    };
  }

  return {
    props: {},
  };
};

const currentDate = new Date();

const Dashboard = () => {
  const router = useRouter();
  const [timeUntil, setTimeUntil] = useState<string | undefined>();
  const [pickResult, setPickResult] = useState<PickResult | undefined>();

  useEffect(() => {
    moment.locale("de");
    setTimeUntil(
      moment(new Date(currentDate.getFullYear(), 12, 25)).fromNow(true)
    );

    fetch("/api/picker", {
      credentials: "same-origin",
    })
      .then((res) => res.json())
      .then((resPickResult) => setPickResult(resPickResult));
  }, []);

  return (
    <Page width={"100vw"} height={"100vh"} margin={0} padding={0}>
      <Head>
        <title>Wichtel-o-Mat - Dashboard ✨</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎅</text></svg>"
        />
      </Head>
      <Grid.Container
        alignItems={"center"}
        justify={"center"}
        height={"100%"}
        padding={0}
        margin={0}
      >
        <Grid xs={24} alignItems={"center"} justify={"center"} width={"375px"}>
          <Card>
            <div
              style={{
                padding: "10px",
                display: "flex",
                alignContent: "center",
                justifyContent: "center",
              }}
            >
              <Image
                src={"/wichtel.svg"}
                alt="Wichtel"
                width={400}
                height={200}
                draggable={false}
              />
            </div>
            <Card.Content>
              <Text h3>
                Willkommen zurück, {pickResult?.person} &mdash;
                <br /> nur noch {timeUntil} verbleiben!
              </Text>
            </Card.Content>
            <Divider w={"100%"} />
            <Card.Content>
              <Display
                shadow
                caption="ist dein Wichtelpartner"
                padding={0}
                margin={0}
              >
                <Text h2 margin={0} style={{ lineHeight: "1em" }}>
                  &rdquo;{pickResult?.pickedPerson || "lädt ..."}&rdquo;
                </Text>
              </Display>
            </Card.Content>
            <Fieldset.Footer>
              <Spacer />
              <Button
                auto
                scale={2 / 3}
                type="error"
                onClick={async () => {
                  await fetch("/api/logout");
                  router.push("/");
                }}
              >
                Logout
              </Button>
            </Fieldset.Footer>
          </Card>
        </Grid>
      </Grid.Container>
    </Page>
  );
};

export default Dashboard;
