import Head from "next/head";
import Image from "next/image";
import {
  Button,
  Card,
  Divider,
  Fieldset,
  Grid,
  Input,
  Page,
  Spacer,
  Text,
  useToasts,
} from "@geist-ui/core";
import { useEffect, useRef, useState } from "react";

import moment from "moment";
import "moment/locale/de";
import { useRouter } from "next/router";
import { GetServerSideProps } from "next";
import { hasValidAuth } from "../lib/login";

export const getServerSideProps: GetServerSideProps = async (context) => {
  if (hasValidAuth(context)) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
      props: {},
    };
  }

  return {
    props: {},
  };
};

const currentDate = new Date();

export default function Home() {
  const router = useRouter();
  const [timeUntil, setTimeUntil] = useState<string | undefined>();
  const { setToast } = useToasts();
  const ref = useRef<HTMLInputElement>();

  useEffect(() => {
    moment.locale("de");
    setTimeUntil(
      moment(new Date(currentDate.getFullYear(), 11, 24)).fromNow(true)
    );
  }, []);

  return (
    <Page dotBackdrop margin={0} padding={0} width={"100vw"}>
      <Head>
        <title>Wichtel-o-Mat ✨</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎅</text></svg>"
        />
      </Head>

      <Grid.Container alignItems={"center"} justify={"center"} height={"100vh"}>
        <Grid xs={22} alignItems={"center"} justify={"center"}>
          <Card padding={0} width={"375px"}>
            <div style={{ padding: "10px" }}>
              <Image
                src={"/wichtel.svg"}
                alt={"Wichtel"}
                width={400}
                height={200}
                draggable={false}
              />
            </div>
            <Card.Content>
              <Text h3>
                Bald ist es wieder soweit! &mdash;
                <br /> Nur noch {timeUntil} verbleiben!
              </Text>
              <Text small>
                Liebe Helfer: innen auch dieses Jahr begrüßen wir euch wieder
                recht Herzlich zum jährlichen Wichtelevent.
              </Text>
              <Text small p>
                Auch dieses Jahr zählt es wieder andere Menschen glücklich zu
                machen und sich dabei selbst über eine kleine Überraschung
                freuen zu können. Daher seid ihr herzlichst eingeladen dieses
                Jahr teilzunehmen!
              </Text>
            </Card.Content>
            <Divider w={"100%"} margin={0} padding={0} />
            <form
              onSubmit={async (e) => {
                e.stopPropagation();
                e.preventDefault();

                const response = await fetch("/api/login", {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                  },
                  body: JSON.stringify({
                    login: ref.current?.value,
                  }),
                });

                if (response.status !== 204) {
                  setToast({
                    text: "Hey du! Du bist noch kein helfender Wichtel, schau später nochmal vorbei!",
                    type: "error",
                  });
                } else {
                  router.push("/dashboard");
                }
              }}
            >
              <Card.Content>
                <Text h5>Login:</Text>
                <Input
                  ref={ref as any}
                  htmlType="text"
                  id="wichtelid"
                  name="wichtelid"
                  label={"Wichtel ID"}
                  placeholder={"DZ50UpXwIp"}
                />
              </Card.Content>
              <Fieldset.Footer>
                <Spacer inline />
                <Button scale={2 / 3} auto htmlType="submit" type={"success"}>
                  Submit
                </Button>
              </Fieldset.Footer>
            </form>
          </Card>
        </Grid>
      </Grid.Container>
    </Page>
  );
}
